JUP-359: fix lint, allow console error,warn and info, remove pnpm test from pre commit moved it to pre-push hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,26 +1,11 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-# Check Prettier standards
-pnpm check-format ||
-(
-    echo 'Prettier format check failed';
-    false;
-)
-
 # Check ESLint Standards
-pnpm lint ||
+pnpm lint:fix ||
 (
-        echo 'Linting failed'
+        echo 'Code format checks failed'
         false; 
 )
-
-# Run Tests 
-pnpm test ||
-(
-        echo 'Tests failed'
-        false; 
-)
-
 # If everything passes... Now we can commit
-echo '✅ Tests, ESlint, Formatting checks passed'
+echo '✅ Formatting checks passed'
